name: Lint GitHub Actions workflow

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**

jobs:
  lint:
    permissions:
      contents: read
    uses: shuymn/github-actions/.github/workflows/gha.yml@5d63b5efe5896eb2d78fa78d20b19f86441e26bb