name: Validate Renovate config

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate.yml
      - .github/renovate.json
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/renovate.yml
      - .github/renovate.json

jobs:
  validate:
    permissions:
      contents: read
    uses: shuymn/github-actions/.github/workflows/renovate.yml@a8738b31f97fc93c8d7254ea6a9524152997bf68
