name: Security checks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  security:
    permissions:
      contents: read
      pull-requests: write
    uses: shuymn/github-actions/.github/workflows/security.yml@a8738b31f97fc93c8d7254ea6a9524152997bf68
