name: Security checks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  security:
    permissions:
      contents: read
      pull-requests: write
    uses: shuymn/github-actions/.github/workflows/security.yml@055d0f5d116beae266cf3356e63dfd52d806abf7