name: Security checks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  security:
    permissions:
      contents: read
      pull-requests: write
    uses: shuymn/github-actions/.github/workflows/security.yml@5d63b5efe5896eb2d78fa78d20b19f86441e26bb